# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from django.contrib import admin

#
class z_gardenAdmin(admin.ModelAdmin):
	model = z_garden

	verbose_name = 'z_garden'
	verbose_name_plural = 'z_gardens'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_ground_typeAdmin(admin.ModelAdmin):
	model = z_ground_type

	verbose_name = 'z_ground_type'
	verbose_name_plural = 'z_ground_types'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_light_typeAdmin(admin.ModelAdmin):
	model = z_light_type

	verbose_name = 'z_light_type'
	verbose_name_plural = 'z_light_types'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_water_levelAdmin(admin.ModelAdmin):
	model = z_water_level

	verbose_name = 'z_water_level'
	verbose_name_plural = 'z_water_levels'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_plantAdmin(admin.ModelAdmin):
	model = z_plant

	verbose_name = 'z_plant'
	verbose_name_plural = 'z_plants'

	inlines = ()
	
	
#
class z_plant_typeAdmin(admin.ModelAdmin):
	model = z_plant_type

	verbose_name = 'z_plant_type'
	verbose_name_plural = 'z_plant_types'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]
	readonly_fields = ('image_tag',)

#
class z_plant_sortAdmin(admin.ModelAdmin):
	model = z_plant_sort

	verbose_name = 'z_plant_sort'
	verbose_name_plural = 'z_plant_sorts'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_plant_ripeAdmin(admin.ModelAdmin):
	model = z_plant_ripe

	verbose_name = 'z_plant_ripe'
	verbose_name_plural = 'z_plant_ripes'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_plant_waterAdmin(admin.ModelAdmin):
	model = z_plant_water

	verbose_name = 'z_plant_water'
	verbose_name_plural = 'z_plant_waters'

	inlines = ()
	
	
	list_display = ('c_name', )
	search_fields = ['c_name', ]

#
class z_garden_yearAdmin(admin.ModelAdmin):
	model = z_garden_year

	verbose_name = 'z_garden_year'
	verbose_name_plural = 'z_garden_years'

	inlines = ()
	
	
#
