# Auto generated from an XMI file
# Do not edit this file
# Edit admin_custom.py instead
from models import *
from admin_generic import *
from admin_custom import *
from django.contrib import admin


#
admin.site.register(z_garden, z_gardenAdmin)
admin.site.register(z_ground_type, z_ground_typeAdmin)
admin.site.register(z_light_type, z_light_typeAdmin)
admin.site.register(z_water_level, z_water_levelAdmin)
admin.site.register(z_plant, z_plantAdmin)
admin.site.register(z_plant_type, z_plant_typeAdmin)
admin.site.register(z_plant_sort, z_plant_sortAdmin)
admin.site.register(z_plant_ripe, z_plant_ripeAdmin)
admin.site.register(z_plant_water, z_plant_waterAdmin)
admin.site.register(z_garden_year, z_garden_yearAdmin)
